device: auto
training_config_path: training
model_config: pany_model
ckpt_path: ckpt/pany.ckpt
model_name: fine_tuned

dataset:
  root: /media/tum/data1/datasets/bop-dataset/lm
  name: lm
  batch_size: 32
  obj_ids: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  target_size: [518, 518]
  depth_scale: 1

mask_type: gt
output_base: /media/tum/data1/datasets/bop-dataset/lm/exp_out

reference:
  base_dir: data/multi-view-references/lm
  pkl_pattern: data/ref_data/lm/pkl/{obj_id}.pkl

inference:
  seed: 42
  top_k: 2
  min_match_threshold: 500
  n_sample_point: 2048
  min_valid_matches: 6
  use_conf: false
  depth_stride: 2
  z_min: 1.0e-6
  z_max:
  intrinsics_stride: 8
  allow_intrinsics_skew: false

outputs:
  match_pattern: match_vis_{scene_id:06d}_{image_id:06d}_{obj_id:06d}.png
  pose_vis_pattern: "{scene_id:06d}_{image_id:06d}_{obj_id:06d}.png"
  pose_results_file: pose_results.csv
  metrics_log_file: log_posed.txt
