dataset:
  root: /media/tum/data1/datasets/bop-dataset/lmo
  name: lmo
  batch_size: 32
  obj_ids: [1, 5, 6, 8, 9, 10, 11, 12]  # LMO objects
  target_size: [518, 518]
  depth_scale: 1 # Scale factor for depth images
  
mask_type: "cnos" # Options: "gt", "cnos"
# ckpt_path: False
ckpt_path: ckpt/last_7500.ckpt
model_name: fine_tuned
model_config: pany_model
output_base: /media/tum/data1/datasets/bop-dataset/lmo/exp_out
